name: Call a reusable workflow and use its outputs

# on:
#   workflow_dispatch:

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

#on:
#  workflow_dispatch:
#    inputs:
#      build_id:
#        required: true
#        type: number
#      deploy_target:
#        required: true
#        type: string
#      perform_deploy:
#        required: true
#        type: boolean

jobs:
  job1:
    uses: ./.github/workflows/build.yaml
    with:
      build_id: "100"
      deploy_target: "foo"


#  job2:
#    runs-on: ubuntu-latest
#    needs: job1
#    steps:
#      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
