name: Reusable workflow

# on:
#   workflow_call:
#     # Map the workflow outputs to job outputs
#     outputs:
#       firstword:
#         description: "The first output string"
#         value: ${{ jobs.example_job.outputs.output1 }}
#       secondword:
#         description: "The second output string"
#         value: ${{ jobs.example_job.outputs.output2 }}

# on:
#   push:
#     branches: [ '*' ]
#   pull_request:
#     branches: [ '*' ]  

on:
  workflow_call:
    inputs:
      build_id:
        required: true
        type: number
      deploy_target:
        required: true
        type: string
      perform_deploy:
        required: true
        type: boolean

jobs:
  parallel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        option:
          - a
          - b
    steps:
      - name: output
        id: output
        run: |
          echo "${{ matrix.option }}=${{ matrix.option }}" >> $GITHUB_OUTPUT
          
  # example_job:
  #   name: Generate output
  #   runs-on: ubuntu-latest
  #   # Map the job outputs to step outputs
  #   outputs:
  #     output1: ${{ steps.step1.outputs.firstword }}
  #     output2: ${{ steps.step2.outputs.secondword }}
  #   steps:
  #     - id: step1
  #       run: echo "firstword=hello" >> $GITHUB_OUTPUT
  #     - id: step2
  #       run: echo "secondword=world" >> $GITHUB_OUTPUT