name: build

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      sceptre-suffix:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      # secondword:
      #   description: "The second output string"
      #   value: ${{ jobs.example_job.outputs.output2 }}

# on:
#   push:
#     branches: [ '*' ]
#   pull_request:
#     branches: [ '*' ]  

# on:
#   workflow_call:

jobs:

#   parallel:
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: true
#       matrix:
#         option:
#           - a
#           - b
#     steps:
#       - name: output
#         id: output
#         run: |
#           echo "${{ matrix.option }}=${{ matrix.option }}" >> $GITHUB_OUTPUT
          
  # example_job:
  #   name: Generate output
  #   runs-on: ubuntu-latest
  #   # Map the job outputs to step outputs
  #   outputs:
  #     output1: ${{ steps.step1.outputs.firstword }}
  #     output2: ${{ steps.step2.outputs.secondword }}
  #   steps:
  #     - id: step1
  #       run: echo "firstword=hello" >> $GITHUB_OUTPUT
  #     - id: step2
  #       run: echo "secondword=world" >> $GITHUB_OUTPUT

  deploy:
    needs: job1
    name: Deploy CloudFormation templates and configure Tower
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-environment:
          - workflows-nextflow-dev
          - workflows-nextflow-prod
          - org-sagebase-strides-ampad-workflows
        include:
          - job-environment: workflows-nextflow-dev
            sceptre-suffix: dev
            tower-url: https://tower-dev.sagebionetworks.org
          - job-environment: workflows-nextflow-prod
            sceptre-suffix: prod
            tower-url: https://tower.sagebionetworks.org
          - job-environment: org-sagebase-strides-ampad-workflows
            sceptre-suffix: ampad
            tower-url: https://tower.sagebionetworks.org
    environment: ${{ matrix.job-environment }}
    outputs:
      output1: ${{ steps.step1.outputs.matrix.sceptre }}
    steps:
      - name: output
        id: output
        run: |
          echo "${{ matrix.sceptre-suffix }}=${{ matrix.sceptre-suffix }}" >> $GITHUB_OUTPUT
          export