name: deploy

# on:
#   workflow_dispatch:

on:
  workflow_run:
    workflows: ["build"]
    branches: ["master"]
    types:
      - completed

# concurrency:
#   group: ${{ github.workflow }}

jobs:
  job2:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
      contents: read    
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
