name: deploy

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  job1:
    uses: ./.github/workflows/build.yaml
  job2:
    runs-on: ubuntu-latest
    needs: job1 
    steps:
      - run: echo ${{ needs.job1.outputs.sceptre-suffix }}  
