name: Call a reusable workflow and use its outputs

# on:
#   workflow_dispatch:

on:
  workflow_run:
    workflows: ["build"]
    branches: ["master"]
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
