name: main



on:
#  push:
#    branches: ['master']
  workflow_run:
    workflows:
      - check
    types:
      - completed

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "main job"
