name: main

on:
  pull_request:
    branches: [ '*' ]
  push:
    paths-ignore:
      - '**.md'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pre-commit"
  jinja-lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "jinja-lint"
  dev:
    if: github.ref == 'refs/heads/main'
    needs:
      - pre-commit
      - jinja-lint
    uses: "./.github/workflows/rw-deploy.yaml"
    secrets: inherit
    with:
      job-environment: "workflows-nextflow-dev"
      sceptre-suffix: "dev"
      tower-url: "https://tower-dev.sagebionetworks.org"
  prod:
    if: github.ref == 'refs/heads/main'
    needs: deploy-dev
    uses: "./.github/workflows/rw-deploy.yaml"
    secrets: inherit
    with:
      job-environment: "workflows-nextflow-prod"
      sceptre-suffix: "dev"
      tower-url: "https://tower.sagebionetworks.org"
  ampad:
    if: github.ref == 'refs/heads/main'
    needs: deploy-prod
    uses: "./.github/workflows/rw-deploy.yaml"
    secrets: inherit
    with:
      job-environment: "worg-sagebase-strides-ampad-workflows"
      sceptre-suffix: "ampad"
      tower-url: "https://tower.sagebionetworks.org"
