name: main



on:
  workflow_run:
    workflows:
      - check
    types:
      - completed
    branches: ['master']
#  push:
#    branches: ['master']

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "main job"
