name: main

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ 'main','develop','staging','prod' ]

jobs:
  mongo-tools-example-steps:
    # The type of runner that the job will run on https://github.com/actions/runner-images/tree/main/images/linux
    runs-on: ubuntu-22.04

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
#          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            synapseclient[pandas,pysftp]
      - name: synapse CLI usage
        run: synapse --help
      # action-mongo-tools without parameters install both : mongo-tools and mongo-shell
      - name: Setup mongo tools - mongo-tools and mongo-shell
        uses: boly38/action-mongo-tools@stable

      - name: Mongo-shell usage - setup mongo user
        # doc: https://docs.mongodb.com/manual/reference/built-in-roles/ "Backup and Restoration Roles"
        # doc: https://docs.mongodb.com/manual/reference/method/db.createUser/
        run: |
          mongosh --version
          mongosh admin --eval 'db.createUser({user:"root",pwd:"mypass",roles:[{"role":"readWrite","db":"myDbForTest"}, "restore"]});'        

      - name: Mongo-tools usage
        run: |
          mongodump --version  
          mongorestore --version
          mongoimport --version
