name: rw-deploy
on:
  workflow_call:
    inputs:
      job-environment:
        required: true
        type: string
      sceptre-suffix:
        required: true
        type: string
      tower-url:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.job-environment }}
    steps:

      - name: Deploy common configuration
        run: >
          echo "pipenv run sceptre --var-file=src/sceptre/variables/${{ inputs.sceptre-suffix }}.yaml"
          echo "launch common --yes"

      - name: Deploy infrastructure configuration
        run: >
          echo "pipenv run sceptre --var-file=src/sceptre/variables/${{ inputs.sceptre-suffix }}.yaml"
          echo "launch infra-${{ inputs.sceptre-suffix }} --yes"

      - name: Deploy projects configuration
        run: >
          echo "pipenv run sceptre --var-file=src/sceptre/variables/${{ inputs.sceptre-suffix }}.yaml"
          echo "launch projects-${{ inputs.sceptre-suffix }} --yes"

      - name: Wait for Nextflow Tower to be up
        run: >
          echo "wait for ${{ inputs.tower-url }}"

      - name: Configure projects in Tower
        run: echo "pipenv run bin/configure-tower-projects.py config/projects-${{ inputs.sceptre-suffix }}"
#        env:
#          NXF_TOWER_TOKEN: ${{ secrets.TOWER_TOKEN }}
#          NXF_TOWER_API_URL: ${{ inputs.tower-url }}/api
